# Generated by Django 5.0.6 on 2024-07-08 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimerState',
        ),
    ]
