# Generated by Django 5.0.6 on 2024-07-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('steam', '0002_delete_timerstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICallCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('last_reset', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
